---
- name: Deploy Traefik changes
  hosts: all
  remote_user: daniel

  tasks:
    - name: Copy Traefik configuration files
      ansible.builtin.copy:
        src: ./deploy/
        dest: "{{ ansible_env.HOME }}/services/traefik"
        mode: "0755"

    - name: Recreate containers
      ansible.builtin.command: |
        docker compose -f {{ ansible_env.HOME }}/services/traefik/docker-compose.yml up -d
      register: docker_compose
      changed_when: docker_compose != 0
