---
- name: Deploy Traefik changes
  hosts: all
  remote_user: daniel

  tasks:
    - name: Add service folder with config folder
      ansible.builtin.shell: |
        install -m 0755 -d services/traefik/config
      register: service_folder
      changed_when: service_folder != 0

    - name: Add compose file
      ansible.builtin.template:
        src: ./templates/docker-compose.yml.j2
        dest: "{{ ansible_env.HOME }}/services/traefik/docker-compose.yml"
        mode: "0755"
      vars:
        api_key: "{{ lookup('env', 'CLOUDFLARE_API_KEY') }}"
        private_host: "{{ lookup('env', 'INTERNAL_DNS_DOMAIN') }}"
        public_host: "{{ lookup('env', 'EXTERNAL_DNS_DOMAIN') }}"

    - name: Add config files
      ansible.builtin.template:
        src: ./{{ item }}.j2
        dest: "{{ ansible_env.HOME }}/services/traefik/{{ item }}"
        mode: "0755"
      loop:
        - config/config.yml
        - config/traefik.yml
      vars:
        private_host: "{{ lookup('env', 'INTERNAL_DNS_DOMAIN') }}"
        public_host: "{{ lookup('env', 'EXTERNAL_DNS_DOMAIN') }}"

    - name: Set permission for acme.json
      ansible.builtin.copy:
        src: acme.json
        dest: "{{ ansible_env.HOME }}/services/traefik/config/acme.json"
        mode: "0600"
        remote_src: false

    - name: Recreate containers
      ansible.builtin.command: |
        docker compose -f {{ ansible_env.HOME }}/services/traefik/docker-compose.yml up -d
      register: docker_compose
      changed_when: docker_compose != 0
