name: "Proxmox Setup VM"

on:
  push:
    branches: 
      - main
    paths:
      - 'proxmox/terraform/*.tf'

  pull_request:
    branches: 
      - main
    paths:
      - 'proxmox/terraform/*.tf'

  workflow_dispatch:
    inputs:
      vm-name:
        description: VM name
        type: string
        required: true
      
      vm-tags:
        description: Tags
        type: string
        default: ''
        required: false

defaults:
  run:
    working-directory: proxmox/terraform

env:
  TF_LOG: "DEBUG"

jobs:
  terraform:
    name: "test, plan, and apply terraform changes"

    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: |
          terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: |
          terraform plan \
            -refresh=true \
            -no-color \
            -input=false \
            -var="PRX_URL=${{ secrets.PRX_URL }}" \
            -var="PRX_API_ID=${{ secrets.PRX_API_TOKEN }}" \
            -var="PRX_API_SECRET=${{ secrets.PRX_API_SECRET }}" \
            -var="PRX_HOST=${{ vars.PRX_HOST }}" \
            -var="PRX_ISO_NAME=${{ vars.PRX_ISO_NAME }}" \
            -var="PRX_STORAGE_NAME=${{ vars.PRX_STORAGE_NAME }}" \
            -var="PRX_VM_NAME=${{ inputs.vm-name || 'debian' }}" \
            -var="PRX_VM_TAGS=${{ inputs.vm-tags }}"
        continue-on-error: true

      - name: Terraform Plan Status
        id: status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          terraform apply
            -auto-approve \
            -input=false \
            -var="PRX_URL=${{ secrets.PRX_URL }}" \
            -var="PRX_API_ID=${{ secrets.PRX_API_TOKEN }}" \
            -var="PRX_API_SECRET=${{ secrets.PRX_API_SECRET }}" \
            -var="PRX_HOST=${{ vars.PRX_HOST }}" \
            -var="PRX_ISO_NAME=${{ vars.PRX_ISO_NAME }}" \
            -var="PRX_STORAGE_NAME=${{ vars.PRX_STORAGE_NAME }}" \
            -var="PRX_VM_NAME=${{ inputs.vm-name || 'debian' }}" \
            -var="PRX_VM_TAGS=${{ inputs.vm-tags }}"
